In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **TASK 1 – Titanic Missing Data**

### Introduction
This task identifies and handles missing values in the Titanic dataset.

Techniques used:
- Median imputation for Age
- Mode imputation for Embarked
- Dropping Cabin column

Median is robust to skew. Mode suits categorical features. Cabin has excessive missing values.

In [5]:
import pandas as pd

df = pd.read_csv('/kaggle/input/competitions/titanic/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df = df.drop(columns=['Cabin'])
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Results & Observations
Missing values handled successfully. Dataset now contains no null values.

# **TASK 2 – Car Evaluation Encoding**

### Introduction
This task encodes categorical variables using Label Encoding and One Hot Encoding.

Label encoding preserves ordinal relationship. One hot encoding avoids artificial ranking.

In [24]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/elikplim/car-evaluation-data-set/car_evaluation.csv',
    header=None
)

df.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [25]:
df.columns = ['buying','maint','doors','persons','lug_boot','safety','class']
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_label = df.copy()

for col in df_label.columns:
    df_label[col] = le.fit_transform(df_label[col])

df_label.head()

   buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [27]:
df_onehot = pd.get_dummies(df, drop_first=True)
df_onehot.head()

,buying_low,buying_med,buying_vhigh,maint_low,maint_med,maint_vhigh,doors_3,doors_4,doors_5more,persons_4,persons_more,lug_boot_med,lug_boot_small,safety_low,safety_med,class_good,class_unacc,class_vgood
0,False,False,True,False,False,True,False,False,False,False,False,False,True,True,False,False,True,False
1,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True,False,True,False
2,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False
3,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False,False,True,False
4,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True,False,True,False

In [28]:
print("Original Shape:", df.shape)
print("Label Encoding Shape:", df_label.shape)
print("One Hot Encoding Shape:", df_onehot.shape)

Original Shape: (1728, 7)
Label Encoding Shape: (1728, 7)
One Hot Encoding Shape: (1728, 18)

# **TASK 3: Feature Scaling – Red Wine Quality Dataset**

### Introduction

This task applies feature scaling to the Red Wine Quality dataset.

Techniques used:
- Standardization
- Normalization

Standardization centers features around zero with unit variance.
Normalization scales features between 0 and 1.

In [43]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/organizations/uciml/red-wine-quality-cortez-et-al-2009/winequality-red.csv',
    sep=','
)

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [44]:
print(df.columns)

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [46]:
X = df.drop('quality', axis=1)
y = df['quality']

In [47]:
X.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_standard = scaler.fit_transform(X)

X_standard_df = pd.DataFrame(X_standard, columns=X.columns)
X_standard_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03,1.599000e+03
mean,3.554936e-16,1.733031e-16,-8.887339e-17,-1.244227e-16,2.132961e-16,-6.221137e-17,4.443669e-17,-3.473172e-14,2.861723e-15,6.754377e-16,1.066481e-16
std,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00,1.000313e+00
min,-2.137045e+00,-2.278280e+00,-1.391472e+00,-1.162696e+00,-1.603945e+00,-1.422500e+00,-1.230584e+00,-3.538731e+00,-3.700401e+00,-1.936507e+00,-1.898919e+00
25%,-7.007187e-01,-7.699311e-01,-9.293181e-01,-4.532184e-01,-3.712290e-01,-8.487156e-01,-7.440403e-01,-6.077557e-01,-6.551405e-01,-6.382196e-01,-8.663789e-01
50%,-2.410944e-01,-4.368911e-02,-5.636026e-02,-2.403750e-01,-1.799455e-01,-1.793002e-01,-2.574968e-01,1.760083e-03,-7.212705e-03,-2.251281e-01,-2.093081e-01
75%,5.057952e-01,6.266881e-01,7.652471e-01,4.341614e-02,5.384542e-02,4.901152e-01,4.723184e-01,5.768249e-01,5.759223e-01,4.240158e-01,6.354971e-01
max,4.355149e+00,5.877976e+00,3.743574e+00,9.195681e+00,1.112703e+01,5.367284e+00,7.375154e+00,3.680055e+00,4.528282e+00,7.918677e+00,4.202453e+00

In [49]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
X_normal = minmax.fit_transform(X)

X_normal_df = pd.DataFrame(X_normal, columns=X.columns)
X_normal_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,0.329171,0.279329,0.270976,0.112247,0.125988,0.209506,0.142996,0.490211,0.449695,0.196496,0.311228
std,0.154079,0.122644,0.194801,0.096570,0.078573,0.147326,0.116238,0.138571,0.121564,0.101501,0.163949
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.221239,0.184932,0.090000,0.068493,0.096828,0.084507,0.056537,0.406021,0.370079,0.131737,0.169231
50%,0.292035,0.273973,0.260000,0.089041,0.111853,0.183099,0.113074,0.490455,0.448819,0.173653,0.276923
75%,0.407080,0.356164,0.420000,0.116438,0.130217,0.281690,0.197880,0.570117,0.519685,0.239521,0.415385
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### Results & Observations

Standardization transformed features to have mean approximately 0 and standard deviation close to 1.

Normalization scaled all features to the range 0 to 1.

Scaling ensures that all features contribute equally during model training.

# **TASK 4: Handling Outliers – Boston Housing Dataset**

### Introduction

This task focuses on detecting and treating outliers in the Boston Housing dataset.

Techniques used:
- Z score method
- IQR method

Z score identifies extreme observations based on standard deviation from the mean.  
The IQR method detects values outside the interquartile range and is more robust for skewed distributions.

In [56]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/arunjangir245/boston-housing-dataset/BostonHousing.csv'
)

df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [57]:
df = df.select_dtypes(include=['number'])

In [58]:
import numpy as np

z_scores = np.abs((df - df.mean()) / df.std())
outliers_z = (z_scores > 3).sum()

outliers_z

crim        8
zn         14
indus       0
chas       35
nox         0
rm          7
age         0
dis         5
rad         0
tax         0
ptratio     0
b          25
lstat       5
medv        0
dtype: int64

In [59]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

outlier_condition = ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR)))
outliers_iqr = outlier_condition.sum()

outliers_iqr

crim       66
zn         68
indus       0
chas       35
nox         0
rm         30
age         0
dis         5
rad         0
tax         0
ptratio    15
b          77
lstat       7
medv       40
dtype: int64

In [60]:
df_clean = df[~outlier_condition.any(axis=1)]
df_clean.shape

(268, 14)

### Results & Observations

Z score method detected extreme values beyond 3 standard deviations.

IQR method identified observations outside interquartile boundaries.

Outliers were removed using IQR to ensure robustness against skewed data.

# **TASK 5: Data Imputation (Adv) Superstore Sales Dataset**

### Introduction

This task handles missing values using advanced imputation techniques.

Techniques used:
- KNN Imputation
- MICE (Iterative Imputer)

These methods estimate missing values using relationships between features rather than simple mean or median replacement.

In [61]:
import os
print(os.listdir('/kaggle/input/datasets'))

['elikplim', 'organizations', 'johnsmith88', 'rohitsahoo', 'arunjangir245', 'lakshmi25npathi']

In [62]:
print(os.listdir('/kaggle/input/datasets/rohitsahoo'))

['sales-forecasting']

In [63]:
print(os.listdir('/kaggle/input/datasets/rohitsahoo/sales-forecasting'))

['train.csv']

In [64]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/rohitsahoo/sales-forecasting/train.csv')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [65]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [66]:
df_numeric = df.select_dtypes(include=['number'])
df_numeric.isnull().sum()

Row ID          0
Postal Code    11
Sales           0
dtype: int64

In [67]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors=5)
df_knn = knn.fit_transform(df_numeric)

import pandas as pd
df_knn = pd.DataFrame(df_knn, columns=df_numeric.columns)

df_knn.isnull().sum()

Row ID         0
Postal Code    0
Sales          0
dtype: int64

In [68]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

mice = IterativeImputer(max_iter=10, random_state=0)
df_mice = mice.fit_transform(df_numeric)

df_mice = pd.DataFrame(df_mice, columns=df_numeric.columns)

df_mice.isnull().sum()

Row ID         0
Postal Code    0
Sales          0
dtype: int64

### Results & Observations

Postal Code had 11 missing values.

KNN imputation filled missing values using nearest neighbor similarity.

MICE estimated missing values iteratively using feature relationships.

Both advanced methods successfully removed missing values.

# **TASK 6: Feature Engineering – Heart Disease Dataset**

### Introduction

This task creates new derived features from the Heart Disease dataset.

Created features:
- Age groups
- Cholesterol categories
- Risk factor feature

Feature engineering enhances interpretability and captures meaningful patterns from existing variables.

In [70]:
import os
print(os.listdir('/kaggle/input/datasets/johnsmith88/heart-disease-dataset'))

['heart.csv']

In [71]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/johnsmith88/heart-disease-dataset/heart.csv')

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [72]:
df.columns = df.columns.str.strip()

In [73]:
df['Age_Group'] = pd.cut(
    df['age'],
    bins=[0, 40, 60, 100],
    labels=['Young', 'Middle', 'Old']
)

df[['age', 'Age_Group']].head()

   age Age_Group
0   52    Middle
1   53    Middle
2   70       Old
3   61       Old
4   62       Old

In [74]:
df['Chol_Category'] = pd.cut(
    df['chol'],
    bins=[0, 200, 240, 600],
    labels=['Normal', 'Borderline', 'High']
)

df[['chol', 'Chol_Category']].head()

   chol Chol_Category
0   212    Borderline
1   203    Borderline
2   174        Normal
3   203    Borderline
4   294          High

In [75]:
df['Risk_Factor'] = df['cp'] + df['thalach']

df[['cp', 'thalach', 'Risk_Factor']].head()

   cp  thalach  Risk_Factor
0   0      168          168
1   0      155          155
2   0      125          125
3   0      161          161
4   0      106          106

### Results & Observations

Age groups and cholesterol categories were derived from continuous variables.

A combined risk factor feature was created from existing clinical variables.

Derived features improve interpretability and enhance representation of patient characteristics.

# **TASK 7: Variable Transformation – Bike Sharing Dataset**

### Introduction

This task applies transformations to reduce skewness in the Bike Sharing dataset.

Techniques used:
- Log transformation
- Square root transformation
- Box Cox transformation

These transformations help stabilize variance and reduce skewness.

In [78]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/lakshmi25npathi/bike-sharing-dataset/day.csv')

df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [79]:
df['cnt'].skew()

np.float64(-0.04735278011900183)

In [80]:
import numpy as np

df['log_cnt'] = np.log1p(df['cnt'])

df['log_cnt'].skew()

np.float64(-1.90755169411613)

In [81]:
df['sqrt_cnt'] = np.sqrt(df['cnt'])

df['sqrt_cnt'].skew()

np.float64(-0.5755272421226963)

In [82]:
from scipy.stats import boxcox

df['boxcox_cnt'], _ = boxcox(df['cnt'] + 1)

df['boxcox_cnt'].skew()

np.float64(-0.1541334084348928)

### Results & Observations

Original variable showed skewness.

Log, square root, and Box Cox transformations reduced skewness.

Box Cox provided the most effective normalization among the applied methods.

# **TASK 8: Feature Selection – Pima Indians Diabetes Dataset**

### Introduction

This task performs feature selection on the Pima Indians Diabetes dataset.

Techniques used:
- Correlation analysis
- Mutual information
- Recursive Feature Elimination

Feature selection reduces dimensionality and improves model efficiency by identifying the most relevant predictors.

In [91]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/organizations/uciml/pima-indians-diabetes-database/diabetes.csv'
)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [92]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

In [93]:
correlation = df.corr()['Outcome'].sort_values(ascending=False)
correlation

Outcome                     1.000000
Glucose                     0.466581
BMI                         0.292695
Age                         0.238356
Pregnancies                 0.221898
DiabetesPedigreeFunction    0.173844
Insulin                     0.130548
SkinThickness               0.074752
BloodPressure               0.065068
Name: Outcome, dtype: float64

In [94]:
from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif(X, y)

mi = pd.Series(mi_scores, index=X.columns).sort_values(ascending=False)
mi

Glucose                     0.122929
BMI                         0.065491
Insulin                     0.058941
Age                         0.042994
BloodPressure               0.021490
Pregnancies                 0.019794
DiabetesPedigreeFunction    0.017552
SkinThickness               0.009015
dtype: float64

In [95]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

rfe = RFE(model, n_features_to_select=5)
rfe.fit(X, y)

selected_features = X.columns[rfe.support_]
selected_features

Index(['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype='object')

### Results & Observations

Correlation analysis identified features most linearly associated with diabetes.

Mutual information measured feature dependency with the outcome.

Recursive Feature Elimination selected the top five most relevant predictors.

# **TASK 9: Handling Imbalanced Data – Credit Card Fraud Detection**

### Introduction

This task addresses class imbalance in the Credit Card Fraud dataset.

Techniques used:
- SMOTE
- ADASYN
- Random undersampling

Imbalanced data can bias models toward the majority class. Resampling techniques help balance class distribution.

In [101]:
print(os.listdir('/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud'))

['creditcard.csv']

In [102]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud/creditcard.csv'
)

df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [103]:
X = df.drop('Class', axis=1)
y = df['Class']

In [104]:
y.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [105]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0)
X_sm, y_sm = smote.fit_resample(X, y)

y_sm.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [106]:
from imblearn.over_sampling import ADASYN

adasyn = ADASYN(random_state=0)
X_ada, y_ada = adasyn.fit_resample(X, y)

y_ada.value_counts()

Class
0    284315
1    284298
Name: count, dtype: int64

In [107]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=0)
X_rus, y_rus = rus.fit_resample(X, y)

y_rus.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

### Results & Observations

The dataset showed strong class imbalance with majority non fraud transactions.

SMOTE and ADASYN generated synthetic minority samples to balance classes.

Random undersampling reduced majority class samples to achieve balance.

# **TASK 10: Combining Multiple Datasets – MovieLens 20M Dataset**

### Introduction

This task combines multiple related datasets from MovieLens.

Datasets merged:
- Ratings
- Movies

Merging datasets creates a richer dataset that links user ratings with movie metadata.

In [111]:
print(os.listdir('/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset'))

['rating.csv', 'link.csv', 'genome_tags.csv', 'genome_scores.csv', 'tag.csv', 'movie.csv']

In [113]:
import pandas as pd

ratings = pd.read_csv(
    '/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset/rating.csv'
)

movies = pd.read_csv(
    '/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset/movie.csv'
)

ratings.head()
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [115]:
merged = pd.merge(ratings, movies, on='movieId')

merged.head()

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [116]:
merged = merged.drop_duplicates()
merged.shape

(20000263, 6)

In [117]:
merged.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
title        0
genres       0
dtype: int64

### Results & Observations

Ratings and movie metadata were successfully merged using movieId.

The merged dataset now links user ratings with movie titles and genres.

Duplicate records were removed to ensure data consistency.

# **TASK 11: Dimensionality Reduction – MNIST Dataset**

### Introduction

This task reduces feature dimensionality in the MNIST dataset.

Techniques used:
- Principal Component Analysis
- t SNE

Dimensionality reduction decreases feature space while retaining important variance.

In [119]:
import pandas as pd

df = pd.read_csv('/kaggle/input/competitions/digit-recognizer/train.csv')

df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [120]:
X = df.drop('label', axis=1)
y = df['label']

In [121]:
from sklearn.decomposition import PCA

pca = PCA(n_components=50)
X_pca = pca.fit_transform(X)

explained_variance = pca.explained_variance_ratio_.sum()
explained_variance

np.float64(0.8255522591802895)

In [122]:
from sklearn.manifold import TSNE

X_subset = X.iloc[:1000]

tsne = TSNE(n_components=2, random_state=0)
X_tsne = tsne.fit_transform(X_subset)

X_tsne.shape

(1000, 2)

### Results & Observations

PCA reduced dimensionality while retaining a significant portion of variance.

t SNE projected high dimensional data into two dimensions for visualization purposes.

Dimensionality reduction decreases computational cost while preserving important structure.

# **TASK 12: Text Preprocessing – IMDB Dataset of 50K Movie Reviews**

### Introduction

This task performs text preprocessing on the IMDB movie reviews dataset.

Steps applied:
- Lowercasing
- Tokenization
- Stopword removal
- Stemming

Text preprocessing prepares raw text data for machine learning models.

In [124]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv'
)

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [126]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

In [128]:
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [ps.stem(word) for word in words if word not in stop_words]
    return ' '.join(words)

In [129]:
df['clean_review'] = df['review'].apply(clean_text)

df[['review', 'clean_review']].head()

,review,clean_review
0,One of the other reviewers has mentioned that ...,one review mention watch oz episod hook right ...
1,A wonderful little production. <br /><br />The...,wonder littl product br br film techniqu unass...
2,I thought this was a wonderful way to spend ti...,thought wonder way spend time hot summer weeke...
3,Basically there's a family where a little boy ...,basic famili littl boy jake think zombi closet...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visual stun film...

### Results & Observations

Text was converted to lowercase and cleaned of non alphabetical characters.

Stopwords were removed to reduce noise.

Stemming reduced words to their root form, improving text normalization.

# **TASK 13: Time Series Preprocessing – UCI Air Quality Dataset**

### Introduction

This task preprocesses time series data in the Air Quality dataset.

Steps applied:
- Handling missing timestamps
- Resampling
- Smoothing using rolling mean

Time series preprocessing ensures consistent intervals and reduces noise.

In [2]:
import pandas as pd

df = pd.read_csv(
    '/kaggle/input/datasets/dakshbhalala/uci-air-quality-dataset/AirQualityUCI.csv',
    sep=','
)

print(df.columns)
print(df.dtypes)

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')
Date              object
Time              object
CO(GT)           float64
PT08.S1(CO)      float64
NMHC(GT)         float64
C6H6(GT)         float64
PT08.S2(NMHC)    float64
NOx(GT)          float64
PT08.S3(NOx)     float64
NO2(GT)          float64
PT08.S4(NO2)     float64
PT08.S5(O3)      float64
T                float64
RH               float64
AH               float64
Unnamed: 15      float64
Unnamed: 16      float64
dtype: object

In [3]:
df = df.drop(columns=['Unnamed: 15', 'Unnamed: 16'])

In [4]:
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

df = df.dropna(subset=['Datetime'])

df = df.set_index('Datetime')

In [5]:
import numpy as np

df = df.replace(-200, np.nan)

In [6]:
df_numeric = df.select_dtypes(include=['float64', 'int64'])

print(df_numeric.columns)

Index(['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)',
       'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)',
       'T', 'RH', 'AH'],
      dtype='object')

In [7]:
df_resampled = df_numeric.resample('h').mean()
df_resampled.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
Datetime,,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [8]:
df_interpolated = df_resampled.interpolate()
df_interpolated.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
Datetime,,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [9]:
df_interpolated['CO_smoothed'] = df_interpolated['CO(GT)'].rolling(window=3).mean()

df_interpolated[['CO(GT)', 'CO_smoothed']].head()

                     CO(GT)  CO_smoothed
Datetime
2004-03-10 18:00:00     2.6          NaN
2004-03-10 19:00:00     2.0          NaN
2004-03-10 20:00:00     2.2     2.266667
2004-03-10 21:00:00     2.2     2.133333
2004-03-10 22:00:00     1.6     2.000000

### Results & Observations

Datetime index was created by combining date and time columns.

Data was resampled to hourly frequency.

Missing values were interpolated.

Rolling mean smoothing reduced short term fluctuations in CO levels.